Gitlab CI: Add help link for static analysis failure.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -936,8 +936,15 @@ Static Analyzer:
       scan_build() {
         scan-build --exclude third_party --exclude _deps --exclude abseil-cpp --exclude benchmark --exclude cpuinfo --exclude eigen --exclude farmhash --exclude fft2d --exclude flatbuffers --exclude flatbuffers-flatc --exclude fp16  --exclude FP16 --exclude FXdiv --exclude psimd  --exclude ml_dtypes --exclude neon2sse  --exclude protobuf --exclude pthreadpool --exclude pthreadpool-source --exclude ruy --exclude xnnpack --exclude XNNPACK  --exclude googletest -o output-${ANALYZER_MODE} -analyzer-config mode=${ANALYZER_MODE} $*
       }
-    - scan_build cmake -B aom_build -GNinja -DCMAKE_BUILD_TYPE=Debug
-    - scan_build --status-bugs cmake --build aom_build
+    - |
+      scan_build cmake -B aom_build -GNinja -DCMAKE_BUILD_TYPE=Debug
+      exit_code=0
+      scan_build --status-bugs cmake --build aom_build || exit_code=$?
+      if [ ${exit_code} -ne 0 ]; then
+        echo "static analyzer HTML warning report can be browsed by following this wiki page:"
+        echo "https://gitlab.com/AOMediaCodec/avm/-/wikis/Reproducing-CI-Test-Failures-Locally#viewing-static-analysis-report-from-gitlab-ci"
+        exit 1
+      fi
   artifacts:
     expire_in: 2 weeks
     when: on_failure
